// <auto-generated />
namespace Learny.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddShortNameInActivityType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddShortNameInActivityType));
        
        string IMigrationMetadata.Id
        {
            get { return "201712081442310_AddShortNameInActivityType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
