// <auto-generated />
namespace Learny.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_document_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_document_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201712011008541_add_document_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
